version: '3.9'

services:
  price-collector-api:
    build: .
    container_name: price_collector_api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
